### ISSUE TITLE
@nativescript-community/ui-chart is not a valid NativeScript plugin. 

### ISSUE THREAD

**Issue by I-NOZex** [nativescript-community/ui-chart#14]
Hi, I'm using this command to add the plugin `tns plugin add @nativescript-community/ui-chart` and it's throwing this error:

`@nativescript-community/ui-chart is not a valid NativeScript plugin. Verify that the plugin package.json file contains a nativescript key and try again.`

My environment:
tns-core-modules.  6.5.18
nativescript. 6.7.8
tns-android has 6.5.3
tns-ios has 6.5.2
nodejs v12.18.3
npm 6.14.6
windows 10 pro 1909 x64

Thank you :)

**Comment by DimitrisRK** [comment]
Hello. Thank you very much for sharing your problem.
This plugin has support for NativeScript 7 applications, while your application runs on 6.5.8.

Unfortunately, there is currently no release for NativeScript 6.x.x version so your only alternative might be updating your existing app, which I strongly recommend.

**Comment by I-NOZex** [comment]
Thank you for the clarification. Upgrade is still not suitable because of some dependencies.
Is there any chart plugin that you could recommend for NS6? (That work with NS Vue both in Android and iOS).

**Comment by DimitrisRK** [comment]
> Thank you for the clarification. Upgrade is still not suitable because of some dependencies.
> Is there any chart plugin that you could recommend for NS6? (That work with NS Vue both in Android and iOS).

In that case, you can try [nativescript-ui-chart](https://www.npmjs.com/package/nativescript-ui-chart) or an older version of it.
There is also [@nativescript/ui-charts](https://www.npmjs.com/package/@nativescript/ui-charts), which is a wrapper of Highcharts. In this case, you may also need to use an older version from npm registry.

Hope these help. :)

**Comment by DimitrisRK** [comment]
@I-NOZex Even though you are using an older version, this issue occurs on NS7 apps as well.
I'm currently looking into this.

**Comment by farfromrefug** [comment]
@I-NOZex just pushed 1.0.2. Hopefully it should fix your issue

**Comment by I-NOZex** [comment]
Thank you :)
