### ISSUE TITLE
Problem building the core demo example

### ISSUE THREAD

**Issue by cjohn001** [nativescript-community/ui-chart#15]
**Summary**
Hello together, I just tried to build the core example of the plugin but was not able to do so. Seems like I am missing some dependencies.

**Expected Behavior**
After cloning the repository and moving to demo folder, I would expect ns run ios to start the demo app

**Possible Solution**
due to the huge amount of error messages, I assume I am missing some dependencies. However, as I have not worked with core yet but angular only, I am not sure how to interpret the messages

**Device (please complete the following information):**
 - IOS Simulator, XCode 12

**Additional Context**
Attached you find the error log:

```
webpack is watching the files…

Hash: 28f72340e80d92a71b6b
Version: webpack 4.44.2
Time: 8515ms
Built at: 10/14/2020 1:06:17 AM
 5 assets
Entrypoint bundle = runtime.js vendor.js bundle.js
Entrypoint tns_modules/@nativescript/core/inspector_modules = runtime.js vendor.js tns_modules/@nativescript/core/inspector_modules.js
[./ sync ^\.\/app\.(css|scss|less|sass)$] . sync nonrecursive ^\.\/app\.(css|scss|less|sass)$ 174 bytes {bundle} [built]
[./ sync recursive (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$] . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$ 816 bytes {bundle} [built]
[./app-root.xml] 309 bytes {bundle} [optional] [built]
[./app.css] 1.27 KiB {bundle} [optional] [built]
[./app.ts] 2.02 KiB {bundle} [built]
[./examples/BarChart.ts] 2.21 KiB {bundle} [optional] [built]
[./examples/BarChart.xml] 1.08 KiB {bundle} [optional] [built]
[./examples/BubbleChart.ts] 1.85 KiB {bundle} [optional] [built]
[./examples/BubbleChart.xml] 1.09 KiB {bundle} [optional] [built]
[./examples/CandleStickChart.ts] 2.58 KiB {bundle} [optional] [built]
[./examples/CandleStickChart.xml] 1.11 KiB {bundle} [optional] [built]
[./examples/HorizontalBarChart.ts] 1.94 KiB {bundle} [optional] [built]
[./examples/HorizontalBarChart.xml] 1.12 KiB {bundle} [optional] [built]
[./examples/LineChart.ts] 1.7 KiB {bundle} [optional] [built]
[./examples/LineChart.xml] 1.08 KiB {bundle} [optional] [built]
    + 457 hidden modules

ERROR in ./examples/PieChart.xml
Module not found: Error: Can't resolve '@nativescript-community/ui-chart' in '/Users/cjohn/Entwicklung/IMS_Help/ui-chart/demo/app/examples'
 @ ./examples/PieChart.xml 1:78-121 2:87-130
 @ . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$
 @ ./app.ts

ERROR in examples/ScatterChart.ts:7:31
TS2307: Cannot find module '@nativescript-community/ui-chart/utils/ColorTemplate' or its corresponding type declarations.
     5 | import { ScatterData } from '@nativescript-community/ui-chart/data/ScatterData';
     6 | import { ScatterDataSet } from '@nativescript-community/ui-chart/data/ScatterDataSet';
  >  7 | import { ColorTemplate } from '@nativescript-community/ui-chart/utils/ColorTemplate';
       |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     8 | 
     9 | function getRandomInt(min, max) {
    10 |     return Math.floor(Math.random() * (max - min + 1)) + min;


```

**Comment by DimitrisRK** [comment]
Hello, thank you very much for posting this issue. I took the liberty to edit your post and shrink error log since it consumed too much space.

There is a slight chance this is an issue caused from 'ui-chart' symlink inside demo example's node_modules/@nativescript-community directory.
I suggest that you try deleting 'ui-chart' symlink folder from node_modules and run 'npm install' inside demo folder anew.

One last resort to test it is removing this line from demo/package.json dependencies:
`"@nativescript-community/ui-chart": "../plugin",`
and try a `tns plugin add @nativescript-community/ui-chart` to install plugin from npmjs registry.

Please have a look at this and let me know if any of these helped.

**Comment by farfromrefug** [comment]
@cjohn001 @DimitrisRK the issue comes from the fact that the plugin is not built yet!
you need to run `npm install; npm run build` in the repo root.

**Comment by DimitrisRK** [comment]
@cjohn001 It's just as farfromrefug says, always perform these 2 steps first.

**Comment by cjohn001** [comment]
Hello together,
thanks a lot. As soon as one does it right it starts to work. Sorry for my stupidity.

**Comment by farfromrefug** [comment]
@cjohn001 nothing stupid here. The doc should mention it.

**Comment by cjohn001** [comment]
@farfromrefug , thanks for the friendly words, but this is something I could have thought about, it is not the first plugin I am working with. I should not start new things at late hours I assume 😂
