### ISSUE TITLE
Render issues on iOS

### ISSUE THREAD

**Issue by alexgritton** [nativescript-community/ui-chart#16]
**Summary**
1. The circles on iOS aren't rendered correctly, see attached image.
![IMG_7F0C00CA633D-1](https://user-images.githubusercontent.com/4497094/97033616-7cac5800-1518-11eb-9593-bd76b3ef55de.jpeg)

 - Device: iPhone XS, and Samsung Galaxy A20
 - Android Version: Android 10
 - iOS Version: 14.0.1
- Nativescript: 7
- ui-chart: 1.1.5

**Additional Context**
My app is an Angular app and these are being rendered under an ngif.

**Comment by farfromrefug** [comment]
You mean they are not centered?

**Comment by alexgritton** [comment]
Yes, they are not centered. On Android they are centered, but on iOS they are not. I'm working on a pull request if you don't have time to get to it.

**Comment by farfromrefug** [comment]
Awesome if you can make a PR!
