### ISSUE TITLE
NS 6 Support

### ISSUE THREAD

**Issue by asharghi** [nativescript-community/ui-chart#22]
Hi @farfromrefug. Any chance making a package for NS 6? If not, do you recommend any other chart plugins working with NS 6?

**Comment by farfromrefug** [comment]
@asharghi there is a 6x version `nativescript-chart` if I am not wrong . however it is not maintained. you could help maintaining it if you want. should be fairly simple to update a n6 branch

**Comment by asharghi** [comment]
For anyone else finding this, looks like this version of `nativescript-ui-chart` works for NS6: https://www.npmjs.com/package/nativescript-ui-chart/v/7.1.1
