### ISSUE TITLE
BarDataSet.setGradientColor renders a light blue bar instead of a gradient

### ISSUE THREAD

**Issue by andresilva-cc** [nativescript-community/ui-chart#23]
**Summary**
Method setGradientColor of BarDataSet does not set gradient, instead, renders a light blue color.

**Expected Behavior**
For example `set.setGradientColor('blue', 'red');` should make a blue/red gradient. I also tried with hexadecimal colors but it also won't work, it keeps showing a light blue color.

**Device (please complete the following information):**
 - Device: Android Emulator
 - Android Version: 11
 - Library Version: 1.1.22

**Comment by farfromrefug** [comment]
@andresilva-cc thanks will look at this. in the meantime you can use a custom renderer (look at the typings for bar chart). in there you can apply a `LinearGradient` to the paint while drawing the bar. (not from N but from the canvas plugin)

**Comment by farfromrefug** [comment]
@andresilva-cc indeed it is not even "plugged" anywhere. I will remove it.
in `1.1.26` i added support for `dataSet.setFillShader(...)` for almost all charts. You can pass a `LineaGradient` from `@nativescript-community/ui-canvas`

**Comment by andresilva-cc** [comment]
@farfromrefug Thanks! I will try that.
