### ISSUE TITLE
highlighting by touch not working when yaxis min and max values are set

### ISSUE THREAD

**Issue by ninahorne** [nativescript-community/ui-chart#25]
**Summary**
If I use 

chart.getAxisLeft().setAxisMinValue(...)
AND
chart.getAxisLeft().sexAxisMaxValue(...)

then highlighting by tough no longer works.  Setting one or neither of these works fine, but I can't use both. 

**Expected Behavior**
highlight per tap will still work with the yAxis minimum and maximum values set.

**Device (please complete the following information):**
 - Device: iPad4 and iPhone 11
 - Library Version: 8.0.2

**Comment by farfromrefug** [comment]
what do you mean by touch? could you share a sample code?

**Comment by ninahorne** [comment]
Sorry, by touch I mean the tap gesture. Right now i'm building on a simulator, so that would be click. 

here is the code that currently does not work:

  ```
setUpChart() {
        const chart = this.chart;
        chart.backgroundColor = "white";

        chart.setTouchEnabled(true);

        chart.setDrawGridBackground(false);

        chart.setDragEnabled(true);
        chart.setScaleEnabled(true);
        chart.setPinchZoom(true);

        chart.getAxisRight().setEnabled(false);
        chart.getAxisLeft().setDrawGridLines(false);
        chart.getAxisLeft().setDrawAxisLine(false);
        chart.getXAxis().setTextColor("grey");
        chart.getXAxis().setPosition(1);
        chart.getXAxis().setDrawGridLines(false);

        chart.setHighlightPerDragEnabled(false);
        chart.setHighlightPerTapEnabled(true);
        chart.setExtraLeftOffset(20);
        chart.setExtraRightOffset(20);
        chart.setExtraBottomOffset(20);

        const myData = this.getChartData();


        const sets = [];
        const set = new LineDataSet(
            myData,
            "RXC Price History",
            "date",
            "price"
        );
        set.setColor('#5d26c1');
        set.setDrawVerticalHighlightIndicator(true);
        set.setDrawHorizontalHighlightIndicator(false);
        set.setDrawCircles(true);
  
        set.setDrawCircleHole(false);
        set.setHighlightEnabled(true);
        
        sets.push(set);


        const ld = new LineData(sets);

        const yAxis = chart.getAxisLeft();

        const yAxisLabels = this.getYAxisLabels();
        const labelFormatter = new CustomPointValueFormatter(yAxisLabels);
        set.setDrawValues(false);
        set.setValueFormatter(labelFormatter);
        set.setCircleRadius(2)

        ld.setValueTextColor("lightgrey");

        const xAxisLabels = this.getXAxisDateLabels();
        const xAxisFormatter = new CustomValueFormatter(xAxisLabels);

        const xAxis = chart.getXAxis();
        xAxis.setValueFormatter(xAxisFormatter);
        xAxis.setLabelRotationAngle(300);
        xAxis.setSpaceMax(0.1);
        xAxis.setSpaceMin(0.1);
        xAxis.setDrawAxisLine(false);

        const yAxisFormatter = new CustomYValueFormatter(yAxisLabels);
        yAxis.setValueFormatter(yAxisFormatter);
        yAxis.setDrawLabels(true);
        yAxis.setStartAtZero(false);
        const maxValue = Math.max.apply(Math, this.rextimatePriceHistories.map(function(o) { return o.amount; })) + 1000;
        const minValue = Math.min.apply(Math, this.rextimatePriceHistories.map(function(o) { return o.amount; })) - 1000;
        yAxis.setAxisMinValue(maxValue)
        yAxis.setAxisMaxValue(minValue)
        
        chart.setData(ld);
        
    }
```



I have found that if i keep `yAxis.setStartAtZero(false)` and comment out `yAxis.setAxisMinValue(...)` and `yAxis.setAxisMaxValue(...)`, highlighting with a tap gesture works fine. If i try to specify a values with those functions, I can only highlight the first point by tap.

**Comment by ninahorne** [comment]
There is a typo in my code about -- I put maxValue for minValue and minValue for maxValue.

**Comment by ninahorne** [comment]
Here is my updated code: 
`    setUpChart() {
        const chart = this.chart;
        chart.backgroundColor = "white";

        chart.setTouchEnabled(true);

        chart.setDrawGridBackground(false);

        chart.setDragEnabled(true);
        chart.setScaleEnabled(true);

        chart.setPinchZoom(true);

        chart.getAxisRight().setEnabled(false);
        chart.getAxisLeft().setDrawGridLines(false);
        chart.getAxisLeft().setDrawAxisLine(false);
        chart.getXAxis().setTextColor("grey");
        chart.getXAxis().setPosition(1);
        chart.getXAxis().setDrawGridLines(false);

        chart.setHighlightPerDragEnabled(false);
        chart.setHighlightPerTapEnabled(true);
        chart.setExtraLeftOffset(20);
        chart.setExtraRightOffset(20);
        chart.setExtraBottomOffset(20);

        const myData = this.getChartData();


        const sets = [];
        const set = new LineDataSet(
            myData,
            "RXC Price History",
            "date",
            "price"
        );
        set.setColor("#5d26c1");
        set.setDrawVerticalHighlightIndicator(true);
        set.setDrawHorizontalHighlightIndicator(false);
        set.setDrawCircles(true);
        set.setDrawCircleHole(false);
        set.setHighlightEnabled(true);
        sets.push(set);

        const ld = new LineData(sets);

        const yAxis = chart.getAxisLeft();

        const yAxisLabels = this.getYAxisLabels();
        const labelFormatter = new CustomPointValueFormatter(yAxisLabels);
        set.setDrawValues(false);
        set.setValueFormatter(labelFormatter);
        set.setCircleRadius(2);

        ld.setValueTextColor("lightgrey");

        const xAxisLabels = this.getXAxisDateLabels();
        const xAxisFormatter = new CustomValueFormatter(xAxisLabels);

        const xAxis = chart.getXAxis();
        xAxis.setValueFormatter(xAxisFormatter);
        xAxis.setLabelRotationAngle(300);
        xAxis.setSpaceMax(0.1);
        xAxis.setSpaceMin(0.1);
        xAxis.setDrawAxisLine(false);

        const yAxisFormatter = new CustomYValueFormatter(yAxisLabels);
        yAxis.setValueFormatter(yAxisFormatter);
        yAxis.setDrawLabels(false);
        yAxis.setStartAtZero(false);
        const maxValue =
            Math.max.apply(
                Math,
                this.rextimatePriceHistories.map(function (o) {
                    return o.amount;
                })
            ) + 1000;
        const minValue =
            Math.min.apply(
                Math,
                this.rextimatePriceHistories.map(function (o) {
                    return o.amount;
                })
            ) - 1000;
        console.log(`maxValue: ${maxValue}`);
        console.log(`minValue: ${minValue}`);

        yAxis.setAxisMinValue(minValue)
        yAxis.setAxisMaxValue(maxValue)

        xAxis.setLabelCount(5);
        xAxis.setAxisMinValue(0);

        chart.setData(ld);

    }
`


it is actually working as intended.  so I'll go head and close this issue. thank you for your quick reply
**FYI: the mistyped code was not the code I was using when I originally had the issue. I am guessing that I had some other settings incorrect or there was just a glitch in my build
