### ISSUE TITLE
PieChart cannot render value

### ISSUE THREAD

**Issue by triple-j-95** [nativescript-community/ui-chart#26]
**Summary**
Thanks for the fantastic work. I think this is a great alternative to nativescript-ui-chart.
Just reporting a small issue where PieChartRenderer crashes with an undefined mValueLinePaint object. In an angular project, this error is ignored and the pie chart is rendered successfully but the label value cannot be displayed due to this problem. 
Demo project included in this repository crashes at below line of PieChartRenderer.ts

```
        if (!this.mValuePaint) {
            this.mValuePaint = new Paint();
            this.mValuePaint.setAntiAlias(true);
            this.mValueLinePaint.setStyle(Style.STROKE); <-- Crashes here.
```

**Expected Behavior**
mValueLinePaint need to be initialized.  

**Device (please complete the following information):**
 - Android Version Pie 9.0

**Comment by farfromrefug** [comment]
@triple-j-95 thanks a lot! should be fixed in 1.1.31
