### ISSUE TITLE
Chart styling 

### ISSUE THREAD

**Issue by mm-psymbl** [nativescript-community/ui-chart#27]
I apologize in advance if this does not respect the guidelines, but i am a bit lost when it comes to styling the chart. 

Specifically how do we control the look of them, like removing the default white background color, etc? I am just looking for pointers...

**Comment by farfromrefug** [comment]
@mm-psymbl look at demo apps. Almost everything is shown there. As for the "doc" there is none per say. Everything is in the typings

**Comment by mm-psymbl** [comment]
@farfromrefug Hey thanks! I checked it out and i have been watching the original documention but for instance I cant seem to find a way to use a custom formatter for x axis with `setValueFormatter` so that i can transform the timestamp values into actual dates. Any chance you might be able to point me in the right direction?

**Comment by farfromrefug** [comment]
@mm-psymbl ok so first i just published this https://nativescript-community.github.io/ui-chart/
For x axis custom format simply do something like this :
```ts
xAxis.setValueFormatter({
    getAxisLabel(value: number, axis: AxisBase) {
       return value;
   }
});
```
