### ISSUE TITLE
Any examples of listening to pan or touch gestures?

### ISSUE THREAD

**Issue by tskweres** [nativescript-community/ui-chart#32]
I have a line chart, and I want to allow the user to drag their finger along the chart, and highlight the y value? i've tried adding (pan) to the <LineChart> element but it does not work. 

Any ideas on how to listen for gestures in an Angular app?

**Comment by farfromrefug** [comment]
@tskweres you simply need to use something like this `https://github.com/nativescript-community/ui-chart/blob/9108923bd5d9dfb8b217067a24d27d65f02915cc/demo_vue/app/examples/Basic.vue#L74`

**Comment by tskweres** [comment]
@farfromrefug  it works! A couple of more questions if you're able to answer, really appreciate the help. 

1. How do I hide the highlight once I'm done dragging? Right now it stays on the chart permenantly
2. Is there a way to hide the horiztonal line of the highlight, so that it's just the vertical?
3. A way to customize the color of the highlight? 

And my app is in Angular, is there a listener where I can get the value of the x & y axis of the highlight in an observable?

![Screen Shot 2021-05-28 at 11 03 04 AM](https://user-images.githubusercontent.com/520309/120012128-b8bf0400-bfa4-11eb-8e26-f36de395d782.png)

**Comment by DiegoMacBD** [comment]
> @farfromrefug it works! A couple of more questions if you're able to answer, really appreciate the help.
> 
> 1. How do I hide the highlight once I'm done dragging? Right now it stays on the chart permanently
>    ** answered:
>    dataSet.setHighlightEnabled(true);
> 2. Is there a way to hide the horiztonal line of the highlight, so that it's just the vertical?
>    ** answered:
>    LineDataSet.setDrawHorizontalHighlightIndicator(false);
> 3. A way to customize the color of the highlight?
>    ** answered
>    LineDataSet.setHighLightColor('#fff');
> 
> And my app is in Angular, is there a listener where I can get the value of the x & y axis of the highlight in an observable? ** answered I am listening to a parent touch event, and getting the value of the LineDataSet.getHighlighted() on each move
> 
> ![Screen Shot 2021-05-28 at 11 03 04 AM](https://user-images.githubusercontent.com/520309/120012128-b8bf0400-bfa4-11eb-8e26-f36de395d782.png)

Can you elaborate on how are you listening to the touch event?

**Comment by farfromrefug** [comment]
@tskweres sorry for the very late answer. I actually missed yours...
* to remove highlight use [highlight](https://nativescript-community.github.io/ui-chart/classes/charts_chart.chart.html#highlight) with a null value
* for the rest you better use a [custom highlighter](https://nativescript-community.github.io/ui-chart/interfaces/charts_linechart.customrenderer.html). You can set only `drawHighlight` if you want.

@DiegoMacBD you enable touch handlers with https://nativescript-community.github.io/ui-chart/classes/charts_chart.chart.html#sethighlightpertapenabled
