### ISSUE TITLE
Axis disappearing on zoom

### ISSUE THREAD

**Issue by xzwiex** [nativescript-community/ui-chart#33]
**Summary**
I trying to create a chart in my app, and see strange behaviour: Bottom axis disappearing on zoom (see video). It's also not reproducing on original mpandroidchart library.

https://user-images.githubusercontent.com/3313259/122921620-5bcc2900-d36b-11eb-88e4-e81c74821dd4.mp4

Here is a sample of code: [Gist](https://gist.github.com/xzwiex/ff7450ca5c8f08ffd97351264297f3ae#file-ui-chart-snippet)

**Device (please complete the following information):**
 - Device: Samsung Galaxy s8, google pixel emulator
 - Android Version 9.0+
 - Library Version 1.1.33

**Comment by farfromrefug** [comment]
@xzwiex could you please try with the latest version?

**Comment by xzwiex** [comment]
@farfromrefug Updated to 1.1.38, same issue.

**Comment by farfromrefug** [comment]
OK thanks will try to reproduce
