### ISSUE TITLE
[Angular] [Android] [BarChart] Bars are not displayed on the last versions of the plugin

### ISSUE THREAD

**Issue by mhtghn** [nativescript-community/ui-chart#38]
**Summary**

On an angular project, I tried using this plugin to display chart. Everything works well on iPhone but on an Android device the BarChart have an issue. The chart is displayed but the bars are not there. Same for the Axis.

On the other side, LineChart are working perfectly on iPhone and Android.

The issue also appears when using CombinedChart that has a BarChart in it. If the CombinedChart has only LineChart it works correctly.

But when I go back to an older version of the plugin the bars are displayed. 

Versions that I tried and  are not working : 1.2.0, 1.2.7 and 1.2.8

Version that I tried and is working : 1.1.43

**Expected Behavior**

The bars should be displayed on Android for the latest version of the plugin

**Comment by farfromrefug** [comment]
@mhtghn is the bar chart working if not in a combined chart?

**Comment by mhtghn** [comment]
@farfromrefug no it does not. The chart is displayed but no bars.

**Comment by farfromrefug** [comment]
@mhtghn just released 1.2.9 which should fix it
let me know

**Comment by mhtghn** [comment]
@farfromrefug Great ! Work as expected. 

Thank you for your work and availability

Closing issue
