### ISSUE TITLE
label.equals is not a function

### ISSUE THREAD

**Issue by DiegoMacBD** [nativescript-community/ui-chart#39]
**Summary**

When calling the LineDataSet 'getDataSetByLabel' method, and sending the correct parameters, I get ERROR: UnhandledError TypeError: label.equals is not a function

**Expected Behavior**

Should return the dataset

**Possible Solution**

I think the code was just translated from java code and that part was missed to translate since equals is not a function on javascript strings.

**Device (please complete the following information):**
 - Device: Doesn't matter.

**Additional Context**

**Comment by farfromrefug** [comment]
@DiegoMacBD thanks for the report! fixed in 1.2.10
