### ISSUE TITLE
TypeError: Cannot read property 'setColor' of undefined

### ISSUE THREAD

**Issue by DiegoMacBD** [nativescript-community/ui-chart#40]
**Summary**

When using the YAxis method setDrawZeroLine(true) and then set any data with LineChart setData method (even if you set empty data) the app will crash and show CONSOLE ERROR: ERROR: UnhandledError TypeError: Cannot read property 'setColor' of undefined, I was not able to trace the error but I think this setColor is the one in in the YAxisRender drawZeroLine method. 

**Expected Behavior**

Shouldn't crash

**Possible Solution**

I think the problem with this is that the zeroLinePaint getter is written like: 
`        if (this.mZeroLinePaint) {
            this.mZeroLinePaint = Utils.getTemplatePaint('gray-stroke');
        }
        return this.mZeroLinePaint;
`
and the porpouse of the 'if' was to set mzeroLinePaint if it was undefined, so it should be easily fixed by changing it to 
`
if (!this.mZeroLinePaint)
`

**Device (please complete the following information):**
 - Device: Doesn't matter

**Additional Context**

**Comment by farfromrefug** [comment]
@DiegoMacBD thanks for the great report again! will fix it right now

**Comment by farfromrefug** [comment]
@DiegoMacBD fixed in 1.2.11

**Comment by DiegoMacBD** [comment]
@farfromrefug Thank you for the quick response!
