### ISSUE TITLE
LineDataSet CircleHole is not working properly.

### ISSUE THREAD

**Issue by DiegoMacBD** [nativescript-community/ui-chart#42]
**Summary**

Im trying to draw a circle with a green inner circle, but it doesn't seem that the inner circle (circle hole) is working properly, im setting it up like this:

highlightDot.setCircleHoleColor(new Color('green'));
highlightDot.setCircleColor(new Color ('white'));
highlightDot.setDrawValues(false);
highlightDot.setCircleRadius(7);
highlightDot.setCircleHoleRadius(6);
highlightDot.setDrawCircles(true);

but the green circle is not displaying correctly, it's just showing a part of it:
![image](https://user-images.githubusercontent.com/84344373/142789397-881e724e-17b5-46ed-9749-9fe4938578c9.png)

Also, both the green circle and white circle look very pixelated. Any help would be appreciated.

**Expected Behavior**

Circle should not have sharp edges, inner circle should render properly.

**Possible Solution**

Maybe a bad implementation of ui-canvas?

**Device**
iOS 15

**Comment by farfromrefug** [comment]
@DiegoMacBD thanks for the report. I ll.take a look this week

**Comment by DiegoMacBD** [comment]
@farfromrefug I found why the inner circle was not rendering properly, fixed it, still looking into why it looks with sharp edges, I will make the PR when I find the solution.

**Comment by farfromrefug** [comment]
@DiegoMacBD it should be fixed in 1.2.12

**Comment by DiegoMacBD** [comment]
Fixed! ty
