### ISSUE TITLE
PieChart differences between android and ios

### ISSUE THREAD

**Issue by vallemar** [nativescript-community/ui-chart#46]
I have a PieChart chart and on ios and android it looks different. I don't know if this is an expected behavior, I think it should look like android.

IOS:
![image](https://user-images.githubusercontent.com/15719383/143954122-dffc5f13-0a78-4bb7-9e01-cb4cde4beeed.png)

ANDROID:
![ANDROID](https://user-images.githubusercontent.com/15719383/143954354-769ed2c9-15f1-4c2f-aa32-a41d0acf0c6a.jpeg)

Code: https://github.com/vallemar/freqtrade-app/blob/master/app/utils/charts/PieChart.ts#L57

You can download the application and run with the sample login data

**Comment by vallemar** [comment]
I have seen that the difference only occurs if chart only have one series, when the graph has more than one it works well

https://github.com/vallemar/freqtrade-app/blob/master/app/utils/charts/PieChart.ts#L76

**Comment by farfromrefug** [comment]
@vallemar not sure why it works on android yet but the issue mostly comes from the fact that you use transparent as hole color. This is not supposed to work. You need to set the hole color as the same as the background color. No other solution yet

**Comment by vallemar** [comment]
@farfromrefug Ok perfect, I think it's a good solution. The strange thing is that when there is more than one series it works

**Comment by farfromrefug** [comment]
@vallemar it is normal seeing how it is coded.

**Comment by vallemar** [comment]
@farfromrefug How?

**Comment by vallemar** [comment]
@farfromrefug refers to the application code is a mess?

**Comment by farfromrefug** [comment]
@vallemar no i am talking about the plugin :) i wont get into details but it is normal

**Comment by vallemar** [comment]
He asked if he thought a good refactor was convenient

**Comment by farfromrefug** [comment]
@vallemar who is he? There is only you and me here :)

**Comment by vallemar** [comment]
@farfromrefug  hahaha sorry my english is very bad! I was referring to you 😂!
