### ISSUE TITLE
Bar Chart not rendering and crashing the app for both ios and android

### ISSUE THREAD

**Issue by nc1401** [nativescript-community/ui-chart#59]
Summary
opening any page with bar chart makes the app crash, with no error logs whatsoever. Tried debugging the data passed to the chart, everything works fine at all breakponts, but app just crashes when the component tries to render the chart on screen.

Expected Behavior
Bar chart should appear with no app crash

Device (please complete the following information):

Device: iphone 15 and android pixel 6 pro
Android Version - API 33
IOS version - ios 17.2
Library Version 1.2.32
nativescript/core version - 8.6.0/8.6.2/8.5.9
nativescript/ios version - 8.5.2/8.6.3/8.6.0
nativescript/android version - 8.5.0

Additional Context

ADD A REWARD using [Speed](speedoss.com) to SOLVE this issue QUICKLY and SUPPORT this project.

**Comment by nc1401** [comment]
[barchartCrashInfo.zip](https://github.com/nativescript-community/ui-chart/files/13857249/barchartCrashInfo.zip)
 Please find the files attached: time-weighted-return is the component using the bar chart. Charts component is the one that renders the chart

**Comment by farfromrefug** [comment]
@nc1401 cant do much with your angular example, sorry. However i did publish a new version which fixes a crash on iOS. Could you try?

**Comment by nc1401** [comment]
@farfromrefug  I just tried the new version 1.2.34, that doesn't help, even on ios. However, I have new information.
The bar chart doesn't fail for all scenarios, it fails only for one case where all the values are negative, for example, if this is the data supplied, the app crashes, if even one of the values is positive, it seems to work.

barData: IChart[] = [
    { label: '', value: '-5.76', index: 0 },
    { label: '', value: '-12.14', index: 1 },
    { label: '', value: '-2.18', index: 2 },
    { label: '', value: '-2.1', index: 3 }
  ];

**Comment by farfromrefug** [comment]
OK could you please create a simple reproducible example project? thar would make it much simpler.
in fact just a function that sets it all up (call from on chart loaded, and with the data !) would be enough

**Comment by nc1401** [comment]
@farfromrefug Sure, I'll post the files in a few minutes!

**Comment by nc1401** [comment]
[chart-repro.zip](https://github.com/nativescript-community/ui-chart/files/13874918/chart-repro.zip)
@farfromrefug here you go, I have attached the relevant files, please ignore any data models etc, I have only attached them in case you need it. 'charts.component.ts' and 'charts.component.html' should have all the basic info you need.

**Comment by nc1401** [comment]
@farfromrefug  I hope this helps, this is the simple function binding for onBarChartLoaded event 

` onBarChartLoaded({ object: barChart }: { object: BarChart }) {
    data = [
        { label: '', value: '-5.76', index: 0 },
        { label: '', value: '-12.14', index: 1 },
        { label: '', value: '-2.18', index: 2 },
        { label: '', value: '-2.1', index: 3 }
    ];
    barRef.setClipValuesToContent(false);

     yAxis = barRef.axisLeft;
     yValues = data.map((dataPoint) => Number(dataPoint.value));

     maxInput = Math.max(...yValues);
     interval = Math.ceil(maxInput / 5);

    yAxis.setForcedInterval(interval);
    yAxis.setAxisMinimum(Math.min(...yValues) - interval);
    yAxis.setAxisMaximum(maxInput + interval);


    barRef.setScaleEnabled(false);

    const barDataSet = new BarDataSet(data, 'Bar Chart', 'index', 'value');
    barDataSet.setDrawValues(true);
    const barDataSets: BarDataSet[] = [barDataSet];
    const barData = new BarData(barDataSets);
    barData.setValueFormatter(new BarDataValueFormatter());
    barData.setBarWidth(0.73);
    barRef.animateXY(750, 750);
   barRef.setData(barData);

}`

**Comment by farfromrefug** [comment]
@nc1401 the error is actually in your code. The plugin just does not handle it well. Your `interval` value is 0.

**Comment by nc1401** [comment]
@farfromrefug  I was about to comment the same, any ideas on how to handle it?

**Comment by farfromrefug** [comment]
@nc1401 a new version is up that fixes the rendering on android and prevent the crash with interval=0

**Comment by nc1401** [comment]
Thank you @farfromrefug ! That's very helpful!
