### ISSUE TITLE
Highlight programmatically

### ISSUE THREAD

**Issue by offizium-berndstorath** [nativescript-community/ui-chart#61]
I simply cannot figure out how to highlight something programmatically.

```javascript
const data = chart.getData()
data.setHighlightEnabled(true)
const dataSet = data.getDataSetByIndex(0)
dataSet.setHighlightEnabled(true)
const v = dataSet.getValues()[0];
chart.highlightValues([{x: v.index, y: v.value}]);
```

Why doesnt this work? How else do I get the values for the highlight?

**Comment by farfromrefug** [comment]
@offizium-berndstorath dont use x,y values.
Do something like this:
```ts
const highlight = {
    dataSetIndex: 0,
    entryIndex: onPathIndex,
    entry: item
};
nChart.highlightValues([highlight]);
```

**Comment by farfromrefug** [comment]
@offizium-berndstorath if you want to select a specific item programmatically then you should know it.
You can also use something like `chartView.getHighlightByXValue()` or `chartView.getHighlightByTouchPoint()`

**Comment by farfromrefug** [comment]
@offizium-berndstorath i dont understand what you want. Please give details. Also you should search in this repo https://github.com/PhilJay/MPAndroidChart. ui-chart is a direct port

**Comment by farfromrefug** [comment]
@offizium-berndstorath ok you have multiple solutions:
* enable draw values with data set has only one point. you can event set a circle for the point 
* use a custom renderer for LineChart(look at the doc) on which you can set a custom `drawLine` in which you can do something special if only one point 
* highlight the point (i suggest with a custom renderer) (first use `getHighlightByXValue` to get it then `highlight` to actually highlight)
